package com.sustav.book;

import com.sustav.book.entity.Book;
import com.sustav.book.service.BookService;
import org.jboss.weld.environment.se.Weld;
import org.jboss.weld.environment.se.WeldContainer;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Weld weld = new Weld();
        WeldContainer container = weld.initialize();
        BookService bookService = container.select(BookService.class).get();
        Book book = bookService.createBook("H2G2", 12.5f, "Book");
        System.out.println(book);
        weld.shutdown();
    }

}
